version: "3.3"

services:
  neo:
    image: neo4j:latest
    # ports:
    #   - 7474:7474
    #   - 7687:7687
    volumes:
      - neo4j_data:/data/
    env_file:
      - .env.neo4j
    networks:
      db_net:
        ipv4_address: 172.16.238.2
        ipv6_address: 2001:3984:3989::11
  bible-reference-api:
    image: dfields2016/bible-reference-explorer-api:master
    depends_on:
      - neo
    ports:
      - 80:8080
    networks:
      db_net:
        ipv4_address: 172.16.238.3
        ipv6_address: 2001:3984:3989::10
volumes:
  neo4j_data:

networks:
  db_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1
